name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: gha-runner-scale-set
    steps:
      - run: lscpu | grep -E 'Socket|Core|Thread|CPU'
      # 1. リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 4. Rubyスクリプトの実行
      - name: Run the Shell script
        run: |
          ./script.sh
